# Generated by Django 4.2 on 2023-05-08 12:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0004_categoryimages_alter_recipe_ingredients'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CategoryImages',
        ),
    ]
