# Generated by Django 4.2 on 2023-05-17 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0009_alter_category_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='body',
            field=models.TextField(),
        ),
    ]
