# Generated by Django 4.2 on 2023-05-18 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0011_recipe_servings'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='site',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
